apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xx1l5it7s-dotnet-basic
  janus-idp.io/tekton: xx1l5it7s-dotnet-basic
  backstage.io/kubernetes-id: xx1l5it7s-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xx1l5it7s-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
